name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deployment script on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: tommaso
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/www/sites/my-cheat-sheet/public
            bash deploy/update-my-cheat-sheet.sh